spring.application.name=eureka-server
server.port=8760


eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false


# Les 2 lignes qui résolvent définitivement ton erreur en 2025
spring.main.allow-beans-of-type-in-client=false
spring.cloud.compatibility-verifier.enabled=false

# Optionnel (dev)
eureka.server.enable-self-preservation=false