###############################################
# AUTH-SERVICE CONFIGURATION
###############################################
spring.application.name=auth-service

server.port=8082


###############################################
# FEIGN CONFIG - COMMUNICATION AVEC USER-SERVICE
###############################################
# URL du microservice user-service
# (En local - http://localhost:8080)
user-service.url=http://localhost:8081

# URL du serveur Eureka (change le port ou l'adresse selon ton cas)
eureka.client.service-url.defaultZone=http://localhost:8760/eureka/

# Facultatif mais fortement recommande en developpement
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

###############################################
# LOGGING
###############################################
logging.level.org.springframework=INFO
logging.level.com.iusjc.authservice=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.feign.client=DEBUG


###############################################
# JACKSON (OPTIONNEL MAIS PROPRE)
###############################################
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false


###############################################
# SECURITY
###############################################
# Aucun filtre de securite ne doit bloquer les routes
# puisque Auth-Service genere les tokens
spring.main.allow-bean-definition-overriding=true

###############################################
# MAIL CONFIGURATION (SMTP)
###############################################
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${BREVO_USER}
spring.mail.password=${BREVO_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


###############################################
# LOGGING DOCKER - DEBUG INTER-SERVICES
###############################################
logging.level.root=INFO
logging.level.com.iusjc.authservice=DEBUG
# Feign - appels vers user-service
logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.feign=DEBUG
logging.level.feign.Logger=DEBUG
# HTTP client
logging.level.org.apache.http=DEBUG
logging.level.org.springframework.web.client=DEBUG
# Eureka
logging.level.org.springframework.cloud.netflix.eureka=DEBUG
logging.level.com.netflix.discovery=DEBUG
# Format des logs
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n
